import { useState, useRef, useEffect } from "react";
import { Send } from "lucide-react";

const MAX_CHARS = 2000;

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled: boolean;
  placeholder?: string;
  queuedMessage?: string | null;
}

const ChatInput = ({ onSend, disabled, placeholder, queuedMessage }: ChatInputProps) => {
  const [value, setValue] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + "px";
    }
  }, [value]);

  const handleSubmit = () => {
    if (!value.trim()) return;
    onSend(value.trim());
    setValue("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newVal = e.target.value;
    if (newVal.length <= MAX_CHARS) {
      setValue(newVal);
    }
  };

  const remaining = MAX_CHARS - value.length;

  return (
    <div className="mx-auto w-full max-w-2xl px-4 pb-4">
      <div
        className="flex items-end gap-2 rounded-2xl border border-border bg-secondary px-4 py-3 cursor-text"
        onClick={() => textareaRef.current?.focus()}
      >
        <textarea
          ref={textareaRef}
          value={value}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          placeholder={disabled && queuedMessage ? "Message queued — will send after response..." : (placeholder || "Send a message...")}
          rows={1}
          className="max-h-[200px] flex-1 resize-none bg-transparent text-sm text-foreground placeholder:text-muted-foreground focus:outline-none"
        />
        <button
          onClick={handleSubmit}
          disabled={!value.trim()}
          className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-30"
        >
          <Send className="h-4 w-4" />
        </button>
      </div>
      <div className="mt-2 flex items-center justify-between px-1">
        <p className="text-xs text-muted-foreground">
          {queuedMessage ? "⏳ Next message queued" : "Responses are generated by AI agents."}
        </p>
        <p className={`text-xs ${remaining < 100 ? "text-destructive" : "text-muted-foreground"}`}>
          {remaining}
        </p>
      </div>
    </div>
  );
};

export default ChatInput;
