import { useState, useRef, useEffect } from "react";
import { ArrowUp } from "lucide-react";

const MAX_CHARS = 2000;

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled: boolean;
  placeholder?: string;
  queuedMessage?: string | null;
}

const ChatInput = ({ onSend, disabled, placeholder, queuedMessage }: ChatInputProps) => {
  const [value, setValue] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = Math.min(textareaRef.current.scrollHeight, 200) + "px";
    }
  }, [value]);

  const handleSubmit = () => {
    if (!value.trim()) return;
    onSend(value.trim());
    setValue("");
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newVal = e.target.value;
    if (newVal.length <= MAX_CHARS) {
      setValue(newVal);
    }
  };

  const remaining = MAX_CHARS - value.length;

  return (
    <div className="border-t border-border bg-background">
      <div className="mx-auto w-full max-w-2xl px-4 py-4">
        <div
          className="flex items-end gap-3 rounded-2xl border border-border bg-secondary/50 px-4 py-3 cursor-text transition-colors focus-within:border-muted-foreground/30 focus-within:bg-secondary"
          onClick={() => textareaRef.current?.focus()}
        >
          <textarea
            ref={textareaRef}
            value={value}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            placeholder={disabled && queuedMessage ? "Message queued — will send after response..." : (placeholder || "Send a message...")}
            rows={1}
            className="max-h-[200px] flex-1 resize-none bg-transparent text-[14px] text-foreground placeholder:text-muted-foreground focus:outline-none"
          />
          <button
            onClick={handleSubmit}
            disabled={!value.trim()}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-foreground text-background transition-all hover:opacity-90 active:scale-95 disabled:opacity-20"
          >
            <ArrowUp className="h-4 w-4" />
          </button>
        </div>
        <div className="mt-2 flex items-center justify-between px-1">
          <p className="text-[11px] text-muted-foreground">
            {queuedMessage ? "⏳ Next message queued" : "Responses are generated by AI agents."}
          </p>
          <p className={`text-[11px] tabular-nums ${remaining < 100 ? "text-destructive" : "text-muted-foreground"}`}>
            {remaining.toLocaleString()}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ChatInput;
